myweb/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="home"),
    url(r'^register$', views.register, name="register"),
    url(r'^(?P<id>[\w-]+)/$', views.details, name="details"),
    url(r'^(?P<id>[\w-]+)/edit/$', views.blog_update, name="update"),
    url(r'^create$', views.article_create, name="create"),
    url(r'^blogs$', views.blogall, name="blogall"),
    url(r'^login$', views.user_login, name="login"),
    url(r'^logout$', views.user_logout, name="logout"),
    url(r'^myblog$', views.myblog, name="myblog"),
]

myweb/myweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', views.index, name="home"),
    # url(r'^register$', views.register, name="register"),
    # url(r'^blog/details$', views.details, name="details"),
    # url(r'^blog/blogs$', views.blogall, name="blogall"),
    # url(r'^login$', views.user_login, name="login"),
    # url(r'^logout$', views.user_logout, name="logout"),
    # url(r'^myblog$', views.myblog, name="myblog"),
    url(r'^blog/', include("blog.urls", namespace='blog')),
    url(r'^change-password$', auth_views.password_change,
        name="chang-password"
        ),
    url(r'^password-change-done$', auth_views.password_change_done,
        {'template_name': 'blog/password_change_done.html'},
        name="password_change_done"
        ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myweb/blog/models.py
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import AbstractUser

from django.conf import settings

from django.core.urlresolvers import reverse
# Create your models here.


class MyUser(AbstractUser):
    score = models.IntegerField(default=0)


def upload_location(instance, filename):
    PostModel = instance.__class__
    # new_id = PostModel.objects.order_by("id").last().id + 1
    """instance.__class__ gets the model Post.
    We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object,
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the
     the post we are creating.
    """
    auth = PostModel.user
    title = PostModel.title
    return "%s/%s/%s" % (auth, title, filename)


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             )
    title = models.CharField(max_length=120)
    content = models.TextField()
    publish = models.DateField(auto_now=False, auto_now_add=True)
    update = models.DateField(auto_now=True, auto_now_add=False)
    image = models.ImageField(upload_to='blogphoto',
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:details", kwargs={'id': self.id})

    class Meta:
        ordering = ["-publish", "-update"]

myweb/blog/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect

from .form import SignupForm, LoginForm, ArticleForm

from django.contrib.auth import get_user_model

from django.contrib.auth import authenticate, login, logout

# from django.contrib.auth import views as auth_views

from django.shortcuts import redirect

from django.contrib import messages
from .models import Article
# Create your views here.


def index(request):
    return render(request, "blog/index.html", {})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('blog:home')
            else:
                messages.warning(request, "用户名或密码错,请重新输入!")
            # usermodel = get_user_model()
            # try:
            #     usermodel.objects.get(
            #         username=username, password=password)
            # except usermodel.DoesNotExist:
            #     messages.warning(request, "用户名或密码错误,请重新输入!")

            # else:
            #     auth_user = usermodel.objects.get(
            #         username=username, password=password)
            #     auth_login(request, auth_user)
            #     return redirect('home')
    else:
        form = LoginForm()
    return render(request, 'blog/login.html', locals())


def user_logout(request):
    logout(request)
    return redirect('blog:home')


def register(request):
    # path = request.get_full_path()
    if request.method == 'POST':
        # data=request.POST
        # print data.get('username')
        form = SignupForm(data=request.POST, auto_id='%s')
        if form.is_valid():
            usermodel = get_user_model()
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = usermodel.objects.create_user(
                username=username,
                email=email,
                password=password
            )
            user.save()
            auth_user = authenticate(username=username, password=password)
            login(request, auth_user)
            # instance = form.save(commit=False)
            # instance.save()
            return redirect("blog:home")
    else:
        form = SignupForm(auto_id='%s')
    return render(request, 'blog/register.html', locals())


def details(request, id=None):
    instance = get_object_or_404(Article, id=id)
    context = {
        'author': instance.user,
        'image': instance.image,
        'title': instance.title,
        'content': instance.content,
        'publish': instance.publish,
        'update': instance.update,
        'id': instance.id
    }
    return render(request, 'blog/details.html', context)


def blogall(request):
    queryset = Article.objects.all()
    if queryset:
        context = {
            'objects': queryset,
        }
        return render(request, 'blog/blogall.html', context)
    else:
        raise Http404


# def myblogdetials(request):
#     username = request.user.username
#     instance = get_object_or_404(Article, user=username)
#     context = {
#         'author': instance.user,
#         'image': instance.image,
#         'title': instance.title,
#         'content': instance.content,
#         'publish': instance.publish,
#         'update': instance.update
#     }
#     return render(request, 'blog/myblog.html', context)

def myblog(request):
    userid = request.user.id
    print "userid:%s" % userid
    queryset = Article.objects.filter(user=userid)
    if not queryset:
        raise Http404
    else:
        context = {
            'objects_list': queryset,
        }
        return render(request, 'blog/myblog.html', context)


def blog_update(request, id=None):
    if not request.user.is_authenticated():
        messages.error(request, "您还没有登录,请登录后再进行编辑!")
        return redirect('blog:login')
    instance = get_object_or_404(Article, id=id)
    if request.user != instance.user:
        raise Http404

    form = ArticleForm(request.POST or None,
                       request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "您的博客更新成功!")
        # return redirect("blog:details")
    # return reverse("blog:details", kwargs={'id': instance.id})
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "instance": instance,
        "form": form
    }
    return render(request, 'blog/articleform.html', context)


def article_create(request):
    if not request.user.is_authenticated():
        messages.error(request, "请您登录后再发布文章!")
        return redirect('blog/login')
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "新文章发布成功!")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'form': form
    }
    return render(request, 'blog/articleform.html', context)

myweb/blog/templates/blog/coming-soon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Coming Soon | Triangle</title>
    <link href="http://apps.bdimg.com/libs/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet"> 
    <link href="css/main.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">

    <!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
    <div class="logo-image">                                
       <a href="index.html"><img class="img-responsive" src="images/logo.png" alt=""> </a> 
    </div>
     <section id="coming-soon">        
         <div class="container">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">                    
                    <div class="text-center coming-content">
                        <h1>UNDER CONSTRUCTION</h1>
                        <p>We have been spending long hours in order to launch our new website. 
                            We will offer freebies, a brand new blog and featured content of our latest work. Join our mailing list or follow us on<br /> Facebook or Twitter to stay up to date.</p>                           
                        <div class="social-link">
                            <span><a href="#"><i class="fa fa-facebook"></i></a></span>
                            <span><a href="#"><i class="fa fa-twitter"></i></a></span>
                            <span><a href="#"><i class="fa fa-google-plus"></i></a></span>
                        </div>
                    </div>                    
                </div>
                <div class="col-sm-12">
                    <div class="time-count">
                        <ul id="countdown">
                            <li class="angle-one">
                                <span class="days time-font">00</span>
                                <p>Days</p>
                            </li>
                            <li class="angle-two">
                                <span class="hours time-font">00</span>
                                <p>Hours</p>
                            </li>
                            <li class="angle-three">
                                <span class="minutes time-font">00</span>
                                <p class="minute">Mins</p>
                            </li>                            
                            <li class="angle-four">
                                <span class="seconds time-font">00</span>
                                <p>Secs</p>
                            </li>               
                        </ul>   
                    </div>
                </div>
            </div>
        </div>       
    </section>
    <section id="subscribe">
        <div class="container">
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2><i class="fa fa-envelope-o"></i> SUBSCRIBE TO OUR NEWSLETTER</h2>
                            <p>Quis filet mignon proident, laboris venison tri-tip commodo brisket aute ut. Tail salami pork belly, flank ullamco bacon bresaola do beef<br /> laboris venison tri-tip.</p>
                        </div>
                        <div class="col-sm-6 newsletter">
                            <form id="newsletter">
                                <input class="form-control" type="email" name="email"  value="" placeholder="Enter Your email">
                                <i class="fa fa-check"></i>
                            </form>
                            <p>Don't worry we will not use your email for spam</p>
                        </div>    
                    </div>
                </div>     
            </div>
        </div> 
    </section>

    <section id="coming-soon-footer" class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center">
                    <p>&copy; Your Company 2014. All Rights Reserved.</p>
                    <p>Designed by Themeum</p>
                </div>
            </div>
        </div>       
    </section>
    

    <script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/1.10.2/jquery.min.js"></script>
    <script type="text/javascript" src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/coundown-timer.js"></script>
    <script type="text/javascript" src="js/wow.min.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <script type="text/javascript">
            //Countdown js
         $("#countdown").countdown({
                date: "10 march 2015 12:00:00",
                format: "on"
            },      
            function() {
                // callback function
        });
    </script>
    
</body>
</html>

myweb/blog/templates/blog/details.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block container %}
    <section id="page-breadcrumb">
        <div class="vertical-center sun">
             <div class="container">
                <div class="row">
                    <div class="action">
                        <div class="col-sm-12">
                            <h1 class="title">Blog Details</h1>
                            
                            <a href="{% url 'blog:update' id %}" class="btn btn-common">编辑</a>
                            
                        </div>                                                                              
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/#page-breadcrumb-->

    <section id="blog-details" class="padding-top">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-7">
                    <div class="row">
                         <div class="col-md-12 col-sm-12">
                            <div class="single-blog blog-details two-column">
                                <div class="post-thumb">
                                    {% if image %}
                                    <a href="#"><img src="{{ image.url }}" class="img-responsive" alt=""></a>
                                    {% endif %}
                                    <div class="post-overlay">
                                        <span class="uppercase"><a href="#">14 <br><small>Feb</small></a></span>
                                    </div>
                                </div>
                                <div class="post-content overflow">
                                    <h2 class="post-title bold"><a href="#">{{ title }}</a></h2>
                                    <h3 class="post-author"><a href="#">Posted by {{ author }}</a></h3>
                                    <p>{{ content }}</p>
                                    <div class="post-bottom overflow">
                                        <ul class="nav navbar-nav post-nav">
                                            <li><a href="#"><i class="fa fa-tag"></i>Creative</a></li>
                                            <li><a href="#"><i class="fa fa-heart"></i>32 Love</a></li>
                                            <li><a href="#"><i class="fa fa-comments"></i>3 Comments</a></li>
                                        </ul>
                                    </div>
                                    <div class="blog-share">
                                        <span class='st_facebook_hcount'></span>
                                        <span class='st_twitter_hcount'></span>
                                        <span class='st_linkedin_hcount'></span>
                                        <span class='st_pinterest_hcount'></span>
                                        <span class='st_email_hcount'></span>
                                    </div>
                                    <div class="author-profile padding">
                                        <div class="row">
                                            <div class="col-sm-2">
                                                <img src="{% static 'blog/images/blogdetails/1.png' %}" alt="">
                                            </div>
                                            <div class="col-sm-10">
                                                <h3>Rodrix Hasel</h3>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi</p>
                                                <span>Website:<a href="www.jooomshaper.com"> www.jooomshaper.com</a></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="response-area">
                                    <h2 class="bold">Comments</h2>
                                    <ul class="media-list">
                                        <li class="media">
                                            <div class="post-comment">
                                                <a class="pull-left" href="#">
                                                    <img class="media-object" src="{% static 'blog/images/blogdetails/2.png' %}" alt="">
                                                </a>
                                                <div class="media-body">
                                                    <span><i class="fa fa-user"></i>Posted by <a href="#">Endure</a></span>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.</p>
                                                    <ul class="nav navbar-nav post-nav">
                                                        <li><a href="#"><i class="fa fa-clock-o"></i>February 11,2014</a></li>
                                                        <li><a href="#"><i class="fa fa-reply"></i>Reply</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="parrent">
                                                <ul class="media-list">
                                                    <li class="post-comment reply">
                                                        <a class="pull-left" href="#">
                                                            <img class="media-object" src="{% static 'blog/images/blogdetails/3.png' %}" alt="">
                                                        </a>
                                                        <div class="media-body">
                                                            <span><i class="fa fa-user"></i>Posted by <a href="#">Endure</a></span>
                                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut </p>
                                                            <ul class="nav navbar-nav post-nav">
                                                                <li><a href="#"><i class="fa fa-clock-o"></i>February 11,2014</a></li>
                                                            </ul>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </li>
                                        <li class="media">
                                            <div class="post-comment">
                                                <a class="pull-left" href="#">
                                                    <img class="media-object" src="{% static 'blog/images/blogdetails/4.png' %}" alt="">
                                                </a>
                                                <div class="media-body">
                                                    <span><i class="fa fa-user"></i>Posted by <a href="#">Endure</a></span>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.</p>
                                                    <ul class="nav navbar-nav post-nav">
                                                        <li><a href="#"><i class="fa fa-clock-o"></i>February 11,2014</a></li>
                                                        <li><a href="#"><i class="fa fa-reply"></i>Reply</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                        
                                    </ul>                   
                                </div><!--/Response-area-->
                                </div>
                            </div>
                        </div>
                    </div>
                 </div>
                <div class="col-md-3 col-sm-5">
                    <div class="sidebar blog-sidebar">
                        <div class="sidebar-item  recent">
                            <h3>Comments</h3>
                            <div class="media">
                                <div class="pull-left">
                                    <a href="#"><img src="{% static 'blog/images/portfolio/project1.jpg' %}" alt=""></a>
                                </div>
                                <div class="media-body">
                                    <h4><a href="#">Lorem ipsum dolor sit amet consectetur adipisicing elit,</a></h4>
                                    <p>posted on  07 March 2014</p>
                                </div>
                            </div>
                            <div class="media">
                                <div class="pull-left">
                                    <a href="#"><img src="{% static 'blog/images/portfolio/project2.jpg' %}" alt=""></a>
                                </div>
                                <div class="media-body">
                                    <h4><a href="#">Lorem ipsum dolor sit amet consectetur adipisicing elit,</a></h4>
                                    <p>posted on  07 March 2014</p>
                                </div>
                            </div>
                            <div class="media">
                                <div class="pull-left">
                                    <a href="#"><img src="{% static 'blog/images/portfolio/project3.jpg' %}" alt=""></a>
                                </div>
                                <div class="media-body">
                                    <h4><a href="#">Lorem ipsum dolor sit amet consectetur adipisicing elit,</a></h4>
                                    <p>posted on  07 March 2014</p>
                                </div>
                            </div>
                        </div>
                        <div class="sidebar-item categories">
                            <h3>Categories</h3>
                            <ul class="nav navbar-stacked">
                                <li><a href="#">Lorem ipsum<span class="pull-right">(1)</span></a></li>
                                <li class="active"><a href="#">Dolor sit amet<span class="pull-right">(8)</span></a></li>
                                <li><a href="#">Adipisicing elit<span class="pull-right">(4)</span></a></li>
                                <li><a href="#">Sed do<span class="pull-right">(9)</span></a></li>
                                <li><a href="#">Eiusmod<span class="pull-right">(3)</span></a></li>
                                <li><a href="#">Mockup<span class="pull-right">(4)</span></a></li>
                                <li><a href="#">Ut enim ad minim <span class="pull-right">(2)</span></a></li>
                                <li><a href="#">Veniam, quis nostrud <span class="pull-right">(8)</span></a></li>
                            </ul>
                        </div>
                        <div class="sidebar-item tag-cloud">
                            <h3>Tag Cloud</h3>
                            <ul class="nav nav-pills">
                                <li><a href="#">Corporate</a></li>
                                <li><a href="#">Joomla</a></li>
                                <li><a href="#">Abstract</a></li>
                                <li><a href="#">Creative</a></li>
                                <li><a href="#">Business</a></li>
                                <li><a href="#">Product</a></li>
                            </ul>
                        </div>
                        <div class="sidebar-item popular">
                            <h3>Latest Photos</h3>
                            <ul class="gallery">
                                <li><a href="#"><img src="{% static 'blog/images/portfolio/popular1.jpg' %}" alt=""></a></li>
                                <li><a href="#"><img src="{% static 'blog/images/portfolio/popular2.jpg' %}" alt=""></a></li>
                                <li><a href="#"><img src="{% static 'blog/images/portfolio/popular3.jpg' %}" alt=""></a></li>
                                <li><a href="#"><img src="{% static 'blog/images/portfolio/popular4.jpg' %}" alt=""></a></li>
                                <li><a href="#"><img src="{% static 'blog/images/portfolio/popular5.jpg' %}" alt=""></a></li>
                                <li><a href="#"><img src="{% static 'blog/images/portfolio/popular1.jpg' %}" alt=""></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/#blog-->
{% endblock container %}
    

myweb/blog/templates/blog/login.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block container %}
{% block home_slider %}
    <section id="page-breadcrumb">
        <div class="vertical-center sun">
             <div class="container">
                <div class="row">
                    <div class="action">
                        <div class="col-sm-12">
                            <h1 class="title">用户登录</h1>
                            <p>请填写用户名和密码</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
   </section>
    <section id="home-slider">
        <div class="container">
            <div class="row">
                <div class="main-slider">
                    <img src="{% static 'blog/images/home/slider/hill.png' %}" class="slider-hill" alt="slider image">
                    <img src="{% static 'blog/images/home/slider/house.png' %}" class="slider-house" alt="slider image">
                    <img src="{% static 'blog/images/home/slider/sun.png' %}" class="slider-sun" alt="slider image">
                    <img src="{% static 'blog/images/home/slider/birds1.png' %}" class="slider-birds1" alt="slider image">
                    <img src="{% static 'blog/images/home/slider/birds2.png' %}" class="slider-birds2" alt="slider image">
                    <div class="slide-text">
                    <form class="form-horizontal" method="post" action="">
		            {% csrf_token %} 
                    	{{ form }}
                    	{% if messages %}
                    	{% for message in messages %}
                        <li><strong>{{ message|escape }}</strong></li>
                        {% endfor %} 
                    	{% endif %}
                    	<div class="form-group">
						  <div class="col-sm-offset-8 col-sm-8">
						    <button type="submit" class="btn btn-primary">登录</button>
						  </div>
						</div>
                    </form>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="preloader"><i class="fa fa-sun-o fa-spin"></i></div>
    </section>
    <!--/#home-slider-->
{% endblock home_slider %}
{% endblock container %}